apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxmox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxmox-exporter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxmox-exporter
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PROXMOX_HOST
              value: {{ .Values.proxmox.host | quote }}
            - name: PROXMOX_USER
              value: {{ .Values.proxmox.user | quote }}
            - name: PROXMOX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-proxmox-credentials
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}