name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin_name: proxmox_monitor
          - target: x86_64-apple-darwin
            os: macos-latest
            bin_name: proxmox_monitor
          - target: aarch64-apple-darwin
            os: macos-latest
            bin_name: proxmox_monitor
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin_name: proxmox_monitor.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install musl-tools (Linux)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt update
          sudo apt install -y musl-tools

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/${{ matrix.bin_name }} dist/proxmox-monitor-${{ matrix.target }}
        if: matrix.os != 'windows-latest'

      - name: Rename binary (Windows)
        run: |
          mkdir dist
          Move-Item target/${{ matrix.target }}/release/${{ matrix.bin_name }} dist/proxmox-monitor-windows-x64.exe
        if: matrix.os == 'windows-latest'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/
          retention-days: 1
          if-no-files-found: error

  # Собираем все артефакты в один архив и публикуем релиз
  upload-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
          merge-multiple: true

      - name: Rename files to friendly names
        run: |
          cd dist
          mv proxmox-monitor-x86_64-unknown-linux-musl proxmox-monitor-linux-x64
          mv proxmox-monitor-x86_64-apple-darwin proxmox-monitor-macos-x64
          mv proxmox-monitor-aarch64-apple-darwin proxmox-monitor-macos-arm64
          # Windows уже с нужным именем
          cd ..

      - name: Create ZIP
        run: |
          cd dist
          zip ../proxmox-monitor-v${{ github.ref_name }}.zip *
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            🎉 Первый стабильный релиз `proxmox-monitor`!

            ## ✨ Что нового
            - CLI для мониторинга Proxmox VE
            - Prometheus Exporter
            - Поддержка Docker и Helm
            - Grafana Dashboard
            - Alerting Rules
            - Полная документация

            ## 📦 Скачать
            Артефакты:
            - `proxmox-monitor-linux-x64`
            - `proxmox-monitor-macos-x64`
            - `proxmox-monitor-macos-arm64`
            - `proxmox-monitor-windows-x64.exe`

            Или установи через Cargo:
            ```bash
            cargo install --git https://github.com/Trytonottry/proxmox_monitor
            ```

            ## 📚 Документация
            👉 https://trytonottry.github.io/proxmox-monitor/

            ## 🐳 Docker
            ```bash
            docker run ghcr.io/trytonottry/proxmox-monitor:latest --help
            ```
          files: proxmox-monitor-v${{ github.ref_name }}.zip
          generate_release_notes: false